apiVersion: v1
kind: Service
metadata:
  name: welcome-ko
spec:
  selector:
    app: greetings
    lang: ko
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: welcome-en
spec:
  selector:
    app: greetings
    lang: en
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: welcome-ch
spec:
  selector:
    app: greetings
    lang: zh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
